# Site Settings
baseurl: ""
url : "https://rodrigogrum.github.io"

# Blog Settings
theme_settings :
  title : Rodrigo Guevara
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Rodrigo Guevara
    description : Accountant and learning data analysis!
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : Excel
      - skill: Tableau
      - skill: PowerBI
        #value : 85  # Percent value
        
  # Icons
  icons :
    email:  r.guevara.rumay@gmail.com
    linkedin:  https://www.linkedin.com/in/rguevararumay/
    github: rodrigogrum
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
